### ISSUE TITLE
PR Training Feedback

### ISSUE THREAD

**Issue by Zavins** [DeepEM-Lab/training#2]
@jqzhou233 Hello Jianqiao! I see that you have created a branch, but you didn't create a pull request. Follow step 9 in the tutorial (https://github.com/DeepEM-Lab/training/tree/main) to create a new Pull Request!

**Comment by jqzhou233** [comment]
Oops! I forgot to git clone the training repository but pushed it directly before. I just created a new branch and a pull request. Am I doing it correctly?

**Comment by Zavins** [comment]
Yep that works. Thank you Jianqiao. The purpose of this training is to teach basic git knowledges and PR technique. You did great!
